### PR TITLE
Initial paper edits

### PR DESCRIPTION
**Pull request by crew102**
This is a WIP on my edits to your paper. It's mostly just rewording stuff. I'm submitting a WIP at this point instead of a complete PR b/c I'm not sure if you're looking for these kind of edits.

One small note: I saw that you introduced line breaks at every 80 chars or so . I removed the newlines, just b/c I find it hard to read the text when it's all chopped up like that, but I know it can be tough to see what's actually change in Git when lines go on for entire paragraphs.

Also FYI, this PR is stacked on top of #20. I believe you'd want to merge that PR first, then squash the changes in this one before merging.

### CODE REVIEW

**Comment by vsoch** [comment]
This is a great idea! I realized when I looked over the PR that I had no actual way of knowing what you had changed, so what I've done is moved each of the paper lines onto one line, so when you make a change it should only be reflected in that line. You can try rebasing with master to see if your edits come through now, or just closing and then fixing the small spelling tweaks again. I'll be programming most of today so let me know what you'd like to do / if you want help!

**Comment by crew102** [comment]
Yes, as I mentioned, it's harder to tell what's changed but I believe it's still a better solution than chopping up the text into lines, as the length of the lines won't stay at 80 chars as edits are made and hence it will get very messy quickly. I've tried the approach you are suggesting (i.e., creating newlines so that changes can more easily be identified) and it just turned out to be a mess.

**Comment by vsoch** [comment]
This was a suggestion to me by the open containers organization and I think it’s a good way to see that if a change is on one line, the entire section isn’t  highlighted. You won’t be able to see it here but if you try opening a new PR and just training one word in a sentence I think it will be more clear.

**Comment by crew102** [comment]
Yeah I know what the appeal is, I just think it's not worth it b/c of the mess it creates. Anyway, feel free to update the text with my edits or not. I only edited about half of the paper so it's not a big deal if you don't want to integrate them.

**Comment by vsoch** [comment]
@crew102 I defintely want to integrate your edits! I can't tell what they are from this PR, this is why I changed the paper.md to have single lines. If you open PR against that, I'd be able to see :)

Here is where I learned this convention: https://github.com/opencontainers/org/pull/9#issuecomment-470639012 I need to be better about updating old docs and sticking to it :)

**Pull request closed without merging**
